config/routes.rb
Rails.application.routes.draw do
  root 'apartments#index'
  resources :apartments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  after_save :calculate_total_price

  def calculate_total_price
    update_columns(total_price: price + common_expenses)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:price, :common_expenses, :total_price, :built_square_meters, :terrace_square_meters, :bedroom_count, :bathroom_count, :near, :comment, :contact_status, :link)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def glyphicon(icon)
    raw %(<span class="glyphicon glyphicon-#{icon}" aria-hidden="true"></span>)
  end
end

app/views/apartments/_form.html.slim
= simple_form_for(@apartment, html: { class: 'vertical-form' }) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :price
  = f.input :common_expenses
  = f.input :built_square_meters
  = f.input :terrace_square_meters
  = f.input :bedroom_count
  = f.input :bathroom_count
  = f.input :near
  = f.input :comment
  = f.input :contact_status
  = f.input :link

  .form-actions
    = f.button :submit

app/views/apartments/edit.html.slim
h1 Editing apartment

== render 'form'

=> link_to 'Show', @apartment
'|
=< link_to 'Back', apartments_path

app/views/apartments/index.html.slim
h1 Listing apartments

table.table.table-condensed.table-striped
  thead
    tr
      th Price
      th Common expenses
      th Total price
      th Built square meters
      th Terrace square meters
      th Bedroom count
      th Bathroom count
      th Near
      th Comment
      th Contact Information
      th Contact status
      th Link
      th
      th
      th

  tbody
    - @apartments.each do |apartment|
      tr
        - truncate_size = 50
        td = apartment.price
        td = apartment.common_expenses
        td = apartment.total_price
        td = apartment.built_square_meters
        td = apartment.terrace_square_meters
        td = apartment.bedroom_count
        td = apartment.bathroom_count
        td = apartment.near.truncate(truncate_size)
        td = apartment.comment.truncate(truncate_size)
        td = apartment.contact_information.try(:truncate, truncate_size)
        td = apartment.contact_status.truncate(truncate_size)
        td = link_to apartment.link.truncate(truncate_size), apartment.link, target: 'blank'
        td = link_to fa_icon('eye'), apartment
        td = link_to fa_icon('edit'), edit_apartment_path(apartment)
        td = link_to fa_icon('trash'), apartment, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Apartment', new_apartment_path, class: 'btn btn-primary'

app/views/apartments/new.html.slim
h1 New apartment

== render 'form'

= link_to 'Back', apartments_path

app/views/apartments/show.html.slim
p#notice = notice

p
  strong Price:
  = @apartment.price
p
  strong Common expenses:
  = @apartment.common_expenses
p
  strong Total price:
  = @apartment.total_price
p
  strong Built square meters:
  = @apartment.built_square_meters
p
  strong Terrace square meters:
  = @apartment.terrace_square_meters
p
  strong Bedroom count:
  = @apartment.bedroom_count
p
  strong Bathroom count:
  = @apartment.bathroom_count
p
  strong Near:
  = @apartment.near
p
  strong Comment:
  = @apartment.comment
p
  strong Contact information
  = @apartment.contact_information
p
  strong Contact status:
  = @apartment.contact_status
p
  strong Link:
  = @apartment.link

=> link_to 'Edit', edit_apartment_path(@apartment)
'|
=< link_to 'Back', apartments_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>